# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
        pip install -r dev_requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        cd tests
        pytest
    - name: Package Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        pyinstaller -n peloton-to-garmin-${{ matrix.os }} --console --clean --noconfirm --add-data 'config.ini;.' --add-data 'README.md;.' peloton-to-garmin.py
    - name: Package MacOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        pyinstaller -n peloton-to-garmin-${{ matrix.os }} --windowed --onedir --clean --noconfirm --add-data 'config.ini:.' --add-data 'README.md:.' peloton-to-garmin.py
    - name: Create Archive Windows
      uses: papeloto/action-zip@v1
      if: ${{ matrix.os == 'windows-latest' }}
      with:
       files: \dist\peloton-to-garmin-${{ matrix.os }}\
       dest: \dist\peloton-to-garmin-${{ matrix.os }}.zip
    - name: Create Archive MacOS
      uses: papeloto/action-zip@v1
      if: ${{ matrix.os == 'macos-latest' }}
      with:
       files: /dist/
       dest: /dist/peloton-to-garmin-${{ matrix.os }}.zip
    - name: Commit changes Windows
      uses: EndBug/add-and-commit@v4
      if: ${{ matrix.os == 'windows-latest' }}
      with:
        message: "Create ${{ matrix.os }} distro"
        add: ${{ github.workspace }}\dist\peloton-to-garmin-${{ matrix.os }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit changes MacOS
      uses: EndBug/add-and-commit@v4
      if: ${{ matrix.os == 'macos-latest' }}
      with:
        message: "Create ${{ matrix.os }} distro"
        add: ${{ github.workspace }}/dist/peloton-to-garmin-${{ matrix.os }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
        
